<a href="https://colab.research.google.com/github/Jamiul-kawsar/ml-interns-2026/blob/main/day2/day2_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [285]:
import pandas as pd

dataset = pd.read_csv('/content/Titanic-Dataset.csv')

In [286]:
dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [287]:
#shape of the dataset
dataset.shape

(891, 12)

In [288]:
dataset.columns
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [289]:
# find missing value
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [290]:
#Feature Engineering
dataset['Title'] = dataset['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)
dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

Drop useless data

In [291]:
dataset = dataset.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
dataset.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked Title
0         0       3    male  22.0      1      0   7.2500        S    Mr
1         1       1  female  38.0      1      0  71.2833        C   Mrs
2         1       3  female  26.0      0      0   7.9250        S  Miss
3         1       1  female  35.0      1      0  53.1000        S   Mrs
4         0       3    male  35.0      0      0   8.0500        S    Mr

handle missing value

In [292]:
# Age
dataset['Age'] = dataset['Age'].fillna(dataset['Age'].median())
dataset.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
Title       0
dtype: int64

In [293]:
# Emnarked
dataset['Embarked'] = dataset['Embarked'].fillna(dataset['Embarked'].mode()[0])
dataset.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Title       0
dtype: int64

Filter female and Group by class

In [294]:
female_dataset = dataset[dataset['Sex'] == 'female']
group_female_dataset = female_dataset.groupby(['Pclass'])
group_female_dataset['Survived'].mean()
# higher class survival chance higher

Pclass
1    0.968085
2    0.921053
3    0.500000
Name: Survived, dtype: float64

In [295]:
#Survival rate of passengers age < 18 by class
young_dataset = dataset[dataset['Age'] < 18]#filter
group_young_dataset = young_dataset.groupby(['Pclass'])# groupby
group_young_dataset['Survived'].mean()# rate

Pclass
1    0.916667
2    0.913043
3    0.371795
Name: Survived, dtype: float64

In [296]:
# Encode
dataset['Sex'] = dataset['Sex'].map({'male': 0, 'female': 1})
dataset = pd.get_dummies(dataset, columns=['Embarked','Title'], drop_first = True)
dataset.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S,Title_Col,...,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,0,3,0,22.0,1,0,7.2500,False,True,False,...,False,False,False,False,False,True,False,False,False,False
1,1,1,1,38.0,1,0,71.2833,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,1,3,1,26.0,0,0,7.9250,False,True,False,...,False,False,True,False,False,False,False,False,False,False
3,1,1,1,35.0,1,0,53.1000,False,True,False,...,False,False,False,False,False,False,True,False,False,False
4,0,3,0,35.0,0,0,8.0500,False,True,False,...,False,False,False,False,False,True,False,False,False,False

Importing sk Learn stuff

In [297]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,precision_score,recall_score,f1_score
from sklearn.preprocessing import StandardScaler

In [298]:
#scale
scaler = StandardScaler()
dataset[['Age', 'Fare']] = scaler.fit_transform(dataset[['Age', 'Fare']])
dataset.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S,Title_Col,...,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,0,3,0,-0.565736,1,0,-0.502445,False,True,False,...,False,False,False,False,False,True,False,False,False,False
1,1,1,1,0.663861,1,0,0.786845,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,1,3,1,-0.258337,0,0,-0.488854,False,True,False,...,False,False,True,False,False,False,False,False,False,False
3,1,1,1,0.433312,1,0,0.420730,False,True,False,...,False,False,False,False,False,False,True,False,False,False
4,0,3,0,0.433312,0,0,-0.486337,False,True,False,...,False,False,False,False,False,True,False,False,False,False

# logistic Model

In [299]:
# split
X = dataset.drop(['Survived'], axis=1)
y = dataset['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# model
log_model = LogisticRegression(max_iter=1000)

# Train
log_model.fit(X_train, y_train)

# Predict
y_pred = log_model.predict(X_test)
y_pred

# prediction report
accur = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("Accuracy: ", accur)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)
print("\n")
print(classification_report(y_test, y_pred))

Accuracy:  0.8156424581005587
Precision:  0.7733333333333333
Recall:  0.7837837837837838
F1 Score:  0.7785234899328859


              precision    recall  f1-score   support

           0       0.85      0.84      0.84       105
           1       0.77      0.78      0.78        74

    accuracy                           0.82       179
   macro avg       0.81      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179



# Random Forest

In [301]:

# split
X = dataset.drop(['Survived'], axis=1)
y = dataset['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# model
ran_model = RandomForestClassifier()

# Train
ran_model.fit(X_train, y_train)

# Predict
y_pred = ran_model.predict(X_test)
y_pred
accur = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("Accuracy: ", accur)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)
print("\n")
print(classification_report(y_test, y_pred))

Accuracy:  0.8324022346368715
Precision:  0.7894736842105263
Recall:  0.8108108108108109
F1 Score:  0.8


              precision    recall  f1-score   support

           0       0.86      0.85      0.86       105
           1       0.79      0.81      0.80        74

    accuracy                           0.83       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.83      0.83      0.83       179