<a href="https://colab.research.google.com/github/Jamiul-kawsar/ml-interns-2026/blob/main/day2/day2_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import pandas as pd

dataset = pd.read_csv('/content/Titanic-Dataset.csv')

In [91]:
dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [92]:
#shape of the dataset
dataset.shape

(891, 12)

In [93]:
dataset.columns
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [94]:
# find missing value
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Drop useless data

In [95]:
dataset = dataset.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
dataset.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

handle missing value

In [96]:
# Age
dataset['Age'] = dataset['Age'].fillna(dataset['Age'].median())
dataset.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [97]:
# Emnarked
dataset['Embarked'] = dataset['Embarked'].fillna(dataset['Embarked'].mode()[0])
dataset.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

Filter female and Group by class

In [98]:
female_dataset = dataset[dataset['Sex'] == 'female']
group_female_dataset = female_dataset.groupby(['Pclass'])
group_female_dataset['Survived'].mean()
# higher class survival chance higher

Pclass
1    0.968085
2    0.921053
3    0.500000
Name: Survived, dtype: float64

In [99]:
#Survival rate of passengers age < 18 by class
young_dataset = dataset[dataset['Age'] < 18]#filter
group_young_dataset = young_dataset.groupby(['Pclass'])# groupby
group_young_dataset['Survived'].mean()# rate

Pclass
1    0.916667
2    0.913043
3    0.371795
Name: Survived, dtype: float64

Importing sk Learn stuff

In [100]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [101]:
dataset['Sex'] = dataset['Sex'].map({'male': 0, 'female': 1})
dataset = pd.get_dummies(dataset, columns=['Embarked'])
dataset.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,0,22.0,1,0,7.2500,False,False,True
1,1,1,1,38.0,1,0,71.2833,True,False,False
2,1,3,1,26.0,0,0,7.9250,False,False,True
3,1,1,1,35.0,1,0,53.1000,False,False,True
4,0,3,0,35.0,0,0,8.0500,False,False,True

Logistic MOdel

In [102]:
# split
X = dataset.drop(['Survived'], axis=1)
y = dataset['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# model
log_model = LogisticRegression()

# Train
log_model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)
y_pred

accuracy_score(y_test, y_pred)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8100558659217877

random forest

In [103]:

# split
X = dataset.drop(['Survived'], axis=1)
y = dataset['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# model
log_model = RandomForestClassifier()

# Train
ran_model.fit(X_train, y_train)

# Predict
y_pred = ran_model.predict(X_test)
y_pred

accuracy_score(y_test, y_pred)

0.8100558659217877